# Numpy Tutorial from ChatGPT (3.5)

prompt: give a tutorial on Numpy

## Introduction to NumPy

NumPy (Numerical Python) is a library used for working with arrays, and it also provides functions for mathematical operations, random number generation, linear algebra, Fourier transforms, and more. It is the foundation for many other scientific computing libraries in Python, such as SciPy, Pandas, and Matplotlib.

## Installation

If you haven't already installed NumPy, you can do so using pip:

In [1]:
pip install numpy

Importing NumPy

To use NumPy, you need to import it. It's customary to import it under the alias `np`:

In [2]:
import numpy as np

## Creating Arrays

1) From a list:

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


2) From a list of lists (creating a 2D array):

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


3) Using built-in functions:

(i) `arange`: Generates an array with a range of values.

In [8]:
c = np.arange(0, 10, 2)  # start, stop, step
print(c)

[0 2 4 6 8]


(ii) `zeros`: Generates an array of zeros.

In [9]:
d = np.zeros((2, 3))  # shape
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


(iii) `ones`: Generates an array of ones.

In [10]:
e = np.ones((3, 4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


(iv) `linspace`: Generates an array of evenly spaced values over a specified range.

In [11]:
f = np.linspace(0, 1, 5)  # start, stop, number of points
print(f)

[0.   0.25 0.5  0.75 1.  ]


## Basic Operations
1. Element-wise operations:

In [15]:
g = np.array([1, 2, 3])
h = np.array([4, 5, 6])

# Addition
print(g + h)

# Subtraction
print(g - h)

# Multiplication
print(g * h)

# Division
print(g / h)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


2. Matrix multiplication:

In [13]:
i = np.array([[1, 2], [3, 4]])
j = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print(np.dot(i, j))

[[19 22]
 [43 50]]


3. Universal functions (ufuncs):

In [14]:
# Square root
print(np.sqrt(g))

# Exponential
print(np.exp(g))

# Sine
print(np.sin(g))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


## Array Manipulation
1. Reshape:

In [16]:
k = np.arange(1, 13)
print(k.reshape((3, 4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Flatten

In [17]:
l = np.array([[1, 2, 3], [4, 5, 6]])
print(l.flatten())

[1 2 3 4 5 6]


3. Transpose

In [18]:
m = np.array([[1, 2], [3, 4], [5, 6]])
print(m.T)

[[1 3 5]
 [2 4 6]]


## Indexing and Slicing

1. Basic indexing:

In [19]:
n = np.array([10, 20, 30, 40, 50])
print(n[0])  # First element
print(n[-1])  # Last element

10
50


2. Slicing

In [20]:
o = np.array([10, 20, 30, 40, 50])
print(o[1:4])  # Elements from index 1 to 3
print(o[:3])  # First three elements
print(o[::2])  # Every second element

[20 30 40]
[10 20 30]
[10 30 50]


3. Boolean Indexing

In [21]:
p = np.array([1, 2, 3, 4, 5])
print(p[p > 2])  # Elements greater than 2

[3 4 5]


## Statistical Operations

In [23]:
q = np.array([[1, 2, 3], [4, 5, 6]])

# Sum
print(np.sum(q))

# Mean
print(np.mean(q))

# Standard deviation
print(np.std(q))

# Minimum
print(np.min(q))

# Maximum
print(np.max(q))

# Sum along an axis
print(np.sum(q, axis=0))  # Sum of columns
print(np.sum(q, axis=1))  # Sum of rows

21
3.5
1.707825127659933
1
6
[5 7 9]
[ 6 15]


## Random Numbers
1. Generate random numbers:

In [25]:
# Random numbers from a uniform distribution over [0, 1)
print(np.random.rand(5))

# Random integers
print(np.random.randint(1, 10, size=(2, 3)))

# Random numbers from a standard normal distribution
print(np.random.randn(4))

[0.260485   0.81330948 0.72086838 0.07507517 0.92912268]
[[7 1 3]
 [8 3 5]]
[-0.04056768  0.91103081 -1.69593509  1.39944974]


2. Seed for reproducibility:

In [26]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


## Saving and Loading Arrays
1. Save to a file:

In [27]:
r = np.array([1, 2, 3])
np.save('my_array.npy', r)

2. Load from a file:

In [28]:
s = np.load('my_array.npy')
print(s)

[1 2 3]
