# Numpy Tutorial from Gemini (1.5)

prompt: give a tutorial on Numpy

NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. It provides powerful tools for working with multi-dimensional arrays and matrices. Here's a basic tutorial to get you started with NumPy:

## 1. Installation:

NumPy is usually included in the scientific Python distribution anaconda. If you don't have it, you can install it using pip:

In [1]:
pip install numpy

## 2. Importing NumPy:

Import NumPy using the following line in your Python script:

In [2]:
import numpy as np

## 3. Creating Arrays:

There are several ways to create NumPy arrays. Here are a few common methods:

- From a list:

In [3]:
data = [1, 2, 3, 4, 5]
arr = np.array(data)
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


- Using built-in functions:

- np.zeros(shape): Creates an array filled with zeros.

- np.ones(shape): Creates an array filled with ones.

- np.empty(shape): Creates an uninitialized array (faster than zeros).

In [4]:
zeros_arr = np.zeros(5)  # Create an array of 5 zeros
print(zeros_arr)  # Output: [0. 0. 0. 0. 0.]

ones_arr = np.ones((3, 2))  # Create a 3x2 array of ones
print(ones_arr)  # Output: [[1. 1.]
                   #        [1. 1.]
                   #        [1. 1.]]

[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


- Using np.arange and np.linspace:

- np.arange(start, stop, step): Creates an array with evenly spaced values within a given interval.

- np.linspace(start, stop, num): Creates an array with a specified number of evenly spaced values over a specified interval.

In [5]:
arr = np.arange(10)  # Create an array from 0 to 9
print(arr)  # Output: [0 1 2 3 4 5 6 7 8 9]

arr = np.linspace(0, 1, 5)  # Create 5 evenly spaced values from 0 to 1
print(arr)  # Output: [0.         0.25       0.5        0.75       1.        ]

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


## 4. Array Properties:

- Shape: The number of dimensions and elements in the array. Use arr.shape to access the shape.

In [6]:
arr = np.arange(12).reshape(3, 4)  # Reshape the array to 3x4
print(arr.shape)  # Output: (3, 4)

(3, 4)


- Data type: The data type of elements in the array. Use arr.dtype to access the data type.

# 5. Basic Operations:

- Arithmetic operations: Addition, subtraction, multiplication, division, etc., work element-wise on arrays of the same shape.

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Output: [5 7 9]

[5 7 9]


- Universal functions: NumPy provides various mathematical functions that operate on arrays element-wise. Examples include np.sin, np.cos, np.exp, etc.

In [7]:
arr = np.array([0, 1, 2])
print(np.sin(arr))  # Output: [0.          0.84147098  0.90929743]

[0.         0.84147098 0.90929743]


# 6. Indexing and Slicing:

Similar to Python lists, NumPy supports indexing and slicing to access specific elements or sub-arrays.

In [9]:
arr = np.arange(10)
print(arr[2])  # Output: 2 (accesses the third element)
print(arr[1:4])  # Output: [1 2 3] (slice from index 1 to 4)

2
[1 2 3]
